### DISCUSSION TITLE
Documentation's sidebar layout

### DISCUSSION THREAD

**Discussion by kpodsiad** [scalameta/metals#3156] [General]
I think there is room for improvement of [metals docs](https://scalameta.org/metals/docs/editors/vscode). For example for me, the sidebar lacks catchy phrases like `getting started` or more emphasized and visible `faq`/`troubleshooting` (it's the last section before e.g. build tools or integrating with the metals. I believe that having such sections could help newcomers get to know metals better.

The new sidebar could look like the following:
```yaml
getting started:
  - install
  - user configuration
  - overview + few words about bloop
text editors:
  - editors...
troubleshooting:
  - same sections as now
build tools:
  - same sections as now
development:
  - contributing to the metals server
  - contributing to the website
  - contributing to the lsp clients
integrating with metals:
  - same sections as now
About:
  - project goals
```
What do you think?

Also, a section about [contributing to the website](https://scalameta.org/metals/docs/contributors/updating-website) mentions the `Edit` button which yields 404 after clicking :/
